framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    templating:
        engines: ['twig']

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: App\Entity\User
    ## Solves bug#4
    from_email:
            address: "webmaster@lequartdheurebordelais.com"
            sender_name: "No Reply"
    registration:
        confirmation:
            enabled:    true 
            template:   FOSUser:Registration:email.txt.twig