homepage:
    path: /
    controller: App\Controller\MainController::index

about:
    path: /about
    controller: App\Controller\MainController::about

contact:
    path: /contact
    controller: App\Controller\MainController::contact

search:
    path: /search
    controller: App\Controller\MainController::search

content_show:
    path: /content/{slug}
    controller: App\Controller\ContentController::show

menu:
    path: /menu
    controller: App\Controller\MenuController::display

tagCloud:
    path: /tagCloud
    controller: App\Controller\MainController::displayTags

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
